kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task03:jane-dev-admin
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    namespace: dev
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io