kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task02:serviceaccounts-pods-review
  namespace: prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pods-read
  apiGroup: rbac.authorization.k8s.io