apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: homework-01-web
spec:
  containers:
    - name: homework-01-web
      image: musisimaru/otus-homework-01
      ports:
        - name: http
          containerPort: 8000
      volumeMounts:
        - name: app
          mountPath: /usr/local/apache2/htdocs/      
  initContainers:
    - name: init-myservice
      image: busybox:1.31.0
      command: ["sh", "-c", "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
